# Header
menu:
  Home: /
  Works: /works
  Archives: /archives
  About: /about

favicon: /favicon.ico

#cover: "http://placehold.it/450x450"

# Logo Image Source
#logo_src: /images/logo.svg
logo_src: /images/logo_s_silhouette.svg

# Theme Main Subtitle
#subtitle_main: This is Phantom, a free, fully responsive site<br />template designed by <a href="http://html5up.net">HTML5 UP</a>.
subtitle_main: レイブン・エンジ

# Theme Secondary subtitle
susbtitle_secondary: レイブン・エンジはウェブデザイン・システム・IoT・人工知能開発などの業務を承ります

# Footer About Section
about_footer: <b>RAVEN ENGI(レイブン・エンジ)</b><br>所在地：東京都荒川区東日暮里<br>事業主：Jerry Lee

# Default post title
default_post_title: Untitled

# Default post cover index page (Recommended)
default_cover_index: "http://placehold.it/450x450"

# Default post cover index page (Optional)
default_cover_detail:

# Show Dates for posts and pages
show_dates:

# Comments. Choose one by filling up the information
comments:
  # Disqus comments
  disqus_shortname: raven-e
  # Facebook comments
  facebook:
    appid:
    comment_count: 5
    comment_colorscheme: light

# Google Analytics Tracking ID
google_analytics: UA-114221746-1

# Social Accounts
twitter_url: https://twitter.com/jerrywdlee
facebook_url: https://www.facebook.com/jerrywdlee
#instagram_url: https://www.instagram.com/
#qq_url: http://wpa.qq.com/msgrd?v=3&uin=827596457&site=qq&menu=yes
#dribble_url: https://dribbble.com/
github_url: https://github.com/jerrywdlee
#googleplus_url: https://plus.google.com/
#behance_url: https://www.behance.net/
#fivehundredpx_url: https://500px.com/
email_url: mailto:jerrywdlee@gmail.com
#rss_url: \#
